CREATE TABLE IF NOT EXISTS salary (
    id SERIAL PRIMARY KEY,
	value NUMERIC(12, 2) NOT NULL
);
CREATE TABLE IF NOT EXISTS employee (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    salary_id INTEGER NOT NULL REFERENCES salary
);